main: com.markiesch.EpicReplant
name: EpicReplant
version: 1.0.0
api-version: 1.17
author: Markiesch

commands:
  epicReplant:
    description: Main command to show help commands
    aliases: [replant, ereplant]